import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import ScrollProvider from "@/context/ScrollProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <ScrollProvider>
        <body className={inter.className}>{children}</body>
      </ScrollProvider>
    </html>
  )
}
